name         'thomasvandoren-pypi'
version      '0.0.1'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-pypi'
dependency   'puppetlabs-apache'
