name         'thomasvandoren-pypi'
version      '0.0.4'
author       'Thomas Van Doren'
summary      'Install and configure internal pypi server.'
description  'Install and configure internal pypi server.'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-pypi'
dependency   'puppetlabs-apache'
dependency   'jamtur01-httpauth'
