name         'thomasvandoren-pypi'
version      '0.0.5'
summary      'Install and configure an internal pypi server.'
description  'Install and configure an internal pypi server.'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-pypi'
dependency   'puppetlabs/apache'
